name: Nightly

on:
  workflow_dispatch:
    inputs:
      patchVersion:
        description: "Format: YYYYMMDDHH"

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Update package.json
        run: |
          set -e
          setSegmentKey="setpath([\"segmentKey\"]; \"${{ secrets.ANALITYCS_KEY }}\")"
          setConfigcatKey="setpath([\"configcatKey\"]; \"${{ secrets.CONFIGCAT_KEY }}\")"
          jqCommands="${setSegmentKey} | ${setConfigcatKey}"
          cat package.json | jq "${jqCommands}" > package.json.tmp
          mv package.json.tmp package.json

      - name: Generate package.json
        run: |
          set -e
          node ./scripts/prepare-nightly-build.js -v ${{ github.event.inputs.patchVersion }}
          mv package.insiders.json package.json

      - name: Package extension
        id: package_vsix
        run: |
          yarn package --pre-release
          echo ::set-output name=vsix_path::$(ls *.vsix)

          version=$(jq --raw-output '.version' package.json)
          echo ::set-output name=version::$version

      - name: Publish to MS Marketplace
        run: |
          npx vsce publish --packagePath ${{ steps.package_vsix.outputs.vsix_path }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      # - name: Publish to Open VSX Registry
      #   run: |
      #     npx ovsx publish --packagePath ${{ steps.package_vsix.outputs.vsix_path }}
      #   env:
      #     OVSX_PAT: ${{ secrets.OPEN_VSX_PAT }}
